window.SiteData = {
  stats: [
    { value: 3,  suffix: '+', icon: 'fas fa-rocket',        label: 'Proyectos públicos', context: 'En GitHub Pages, live' },
    { value: 4,  suffix: '',  icon: 'fas fa-hourglass-half', label: 'Años aprendiendo',   context: 'AIEP · autodidacta' },
    { value: 12, suffix: '+', icon: 'fas fa-layer-group',    label: 'Tecnologías',        context: 'Frontend, backend, DB' },
    { value: 5,  suffix: '',  icon: 'fas fa-certificate',    label: 'Certificaciones',    context: 'Microsoft Learn · NetAcad' },
  ],
  skills: [
    ['HTML & CSS', 90],
    ['JavaScript', 50],
    ['Python', 60],
    ['PHP & MySQL', 65],
    ['Git & GitHub', 70],
    ['Linux / Wazuh', 55],
  ],
  skillTags: ['HTML','CSS','Bootstrap','JavaScript','Python','PHP','C#','MySQL','SQL Server','Git','GitHub','Linux','Wazuh','Google Sites','XAMPP'],
  projects: [
    {
      id: 'hydro',
      title: 'Hydro-Conecta',
      type: 'Sitio web · proyecto de especialidad',
      summary: 'Plataforma web para monitoreo y conexión de servicios hidráulicos. Mezcla landing pública, backend administrativo y panel de operaciones para reportar consumo y eventos.',
      cats: ['Full Stack'],
      tags: ['HTML', 'CSS', 'JavaScript', 'Python', 'PHP'],
      demo: 'https://whitemooncy.github.io/PROYECTO-DE-ESPECIALIDAD/',
      repo: 'https://github.com/WhiteMooncy/PROYECTO-DE-ESPECIALIDAD',
    },
    {
      id: 'cafe',
      title: 'Cafetería',
      type: 'Sitio web admin',
      summary: 'Sitio web administrativo de una cafetería: catálogo de productos, gestión de stock, autenticación de empleados y panel de pedidos. Backend en PHP + MySQL.',
      cats: ['Backend', 'Full Stack'],
      tags: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
      demo: 'https://whitemooncy.github.io/Web-Admin/',
      repo: 'https://github.com/WhiteMooncy/Web-Admin',
    },
    {
      id: 'akelarre',
      title: 'Akelarre',
      type: 'Sitio web',
      summary: 'Sitio web temático con identidad visual fuerte y secciones narrativas. Explora animaciones CSS y diseño editorial.',
      cats: ['Frontend'],
      tags: ['HTML', 'CSS', 'JavaScript'],
      demo: 'https://whitemooncy.github.io/Akelarre/',
      repo: 'https://github.com/WhiteMooncy/Akelarre',
    },
  ],
};
